import {
  LOCAL_API_HOSTNAME,
  LOCAL_API_PORT,
  LOCAL_API_VERSION,
  LOCAL_API_PATH_LOGIN,
  LOCAL_API_PATH_REGISTER,
  LOCAL_API_PATH_USER,
  LOCAL_API_PATH_PRODUCT,
  LOCAL_API_PATH_VARIAN,
  LOCAL_API_PATH_CART,
} from '@env';

export default {
  LOCAL_API_HOSTNAME,
  LOCAL_API_PORT,
  LOCAL_API_VERSION,
  LOCAL_API_PATH_LOGIN,
  LOCAL_API_PATH_REGISTER,
  LOCAL_API_PATH_USER,
  LOCAL_API_PATH_PRODUCT,
  LOCAL_API_PATH_VARIAN,
  LOCAL_API_PATH_CART,
};
